export default {
  CREATE_NEW_GAME: 'CREATE_GAME',
  JOIN_GAME: 'JOIN_GAME',
  ANSWER_QUESTION: 'ANSWER_QUESTION',
  GET_LIST_GAME: 'GET_LIST_GAME',
  SET_GAME_MODE: 'SET_GAME_MODE',
  SET_GAME_CHARACTER: 'SET_GAME_CHARACTER',
  SET_RIVAL_CHARACTER: 'SET_RIVAL_CHARACTER'
}
