package socket;

public enum GameAction {
    LOGIN,
    CREATE_GAME,
    JOIN_GAME,
    GUEST_JOIN_GAME,
    ANSWER,
    POWER,
    GET_LIST_GAMES,
    GET_ONLINE_USERS, 
    SET_GAME_MODE,
    DONE_CHOOSE_MODE,
    SET_GAME_CHARACTER,
    SET_RIVAL_CHARACTER,
    START_GAME,
    GUEST_READY,
    LEAVE_GAME,
    GUEST_LEAVE_GAME,
    GET_GAME_STATE,
    BE_HIT,
    INVITE,
    REPLY_INVITATION,
    DECLINE_INVITATION
}
