package socket;

public enum GameAction {
    CREATE_GAME,
    JOIN_GAME,
    GUEST_JOIN_GAME,
    ANSWER_QUESTION,
    GET_LIST_GAMES,
    GET_ONLINE_USERS, 
    SET_GAME_MODE,
    DONE_CHOOSE_MODE,
    SET_GAME_CHARACTER,
    SET_RIVAL_CHARACTER,
    START_GAME,
    GUEST_READY,
    LEAVE_GAME,
    GET_GAME_STATE,
    BE_HIT,
    INVITE,
}
